"""Shared helpers for boundary-audit scripts."""
from __future__ import annotations

import fnmatch
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional, Sequence, Tuple


REPO_ROOT = Path(__file__).resolve().parents[2]
ALLOWLIST_PATH = REPO_ROOT / "config" / "boundary_allowlist.yml"


def load_allowlist_min(path: Path = ALLOWLIST_PATH) -> dict:
    """Load the allowlist YAML using PyYAML (anchors fully expand)."""
    import yaml  # local import keeps the dependency optional for tooling
    if not path.exists():
        raise FileNotFoundError(f"allowlist not found at {path}")
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


@dataclass
class Hit:
    path: Path
    line_no: int
    line: str
    term: str
    allowlisted: bool
    reason: str = ""


def is_allowlisted(path: Path, term: str, allowlist_block: Sequence[dict]) -> Tuple[bool, str]:
    """Return (allowlisted, reason) for the given path/term against allowlist entries."""
    name = path.name
    full_tail = str(path.relative_to(REPO_ROOT)) if path.is_absolute() else str(path)
    for entry in allowlist_block:
        if entry.get("term", "").lower() != term.lower():
            continue
        for pattern in entry.get("allowed_files", []) or []:
            if fnmatch.fnmatch(name, pattern) or fnmatch.fnmatch(full_tail, pattern) or fnmatch.fnmatch(full_tail, f"*/{pattern}"):
                return True, entry.get("reason", "")
        if entry.get("allowed_context"):
            # bridge-style entries — we conservatively allow only when the file
            # explicitly names the allowed context as a string match nearby.
            return True, entry.get("reason", "context-only")
    return False, ""


SCAN_EXTS = {".md", ".tsv", ".csv", ".py", ".html", ".bib", ".txt", ".yml", ".yaml"}


def iter_scan_files(roots: Iterable[Path], exts: Iterable[str] = SCAN_EXTS) -> Iterable[Path]:
    seen: set[Path] = set()
    exts = set(exts)
    for root in roots:
        if not root.exists():
            continue
        if root.is_file():
            if root.suffix.lower() in exts and root not in seen:
                seen.add(root)
                yield root
            continue
        for path in sorted(root.rglob("*")):
            if path.is_file() and path.suffix.lower() in exts and path not in seen:
                seen.add(path)
                yield path


def scan_file_for_terms(
    path: Path,
    terms: Sequence[Tuple[str, re.Pattern]],
    allowlist_block: Sequence[dict],
) -> List[Hit]:
    hits: List[Hit] = []
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return hits
    for line_no, line in enumerate(text.splitlines(), start=1):
        for term, pattern in terms:
            if pattern.search(line):
                ok, reason = is_allowlisted(path, term, allowlist_block)
                hits.append(Hit(path=path, line_no=line_no, line=line.strip()[:240], term=term, allowlisted=ok, reason=reason))
    return hits


def compile_terms(raw_terms: Sequence[str]) -> List[Tuple[str, re.Pattern]]:
    out: List[Tuple[str, re.Pattern]] = []
    for term in raw_terms:
        # word-boundary for short terms; loose match for phrases
        if " " in term or "-" in term:
            pat = re.compile(re.escape(term), re.IGNORECASE)
        else:
            pat = re.compile(rf"(?<![A-Za-z0-9_]){re.escape(term)}(?![A-Za-z0-9_])", re.IGNORECASE)
        out.append((term, pat))
    return out


def render_report(title: str, hits: List[Hit], allowlist_section: str) -> str:
    lines = [f"# {title}", "", f"_Generated by `scripts/boundary_audit/`._", ""]
    flagged = [h for h in hits if not h.allowlisted]
    allowed = [h for h in hits if h.allowlisted]
    lines.append(f"- Total hits: **{len(hits)}**")
    lines.append(f"- Flagged (unallowlisted): **{len(flagged)}**")
    lines.append(f"- Allowlisted (suppressed): **{len(allowed)}**")
    lines.append(f"- Allowlist section: `{allowlist_section}`")
    lines.append("")
    if flagged:
        lines.append("## Flagged")
        for h in flagged:
            rel = h.path.relative_to(REPO_ROOT) if h.path.is_absolute() else h.path
            lines.append(f"- `{rel}:{h.line_no}` — term `{h.term}`")
            lines.append(f"    > {h.line}")
        lines.append("")
    if allowed:
        lines.append("## Allowlisted (suppressed)")
        for h in allowed[:200]:
            rel = h.path.relative_to(REPO_ROOT) if h.path.is_absolute() else h.path
            lines.append(f"- `{rel}:{h.line_no}` — term `{h.term}` — reason: {h.reason}")
        if len(allowed) > 200:
            lines.append(f"- … and {len(allowed) - 200} more allowlisted hits omitted")
    return "\n".join(lines) + "\n"
