"""F3-A: Final manuscript v2 audit — word count, figure refs, statistical claims, internal consistency."""
from v17p35_SYNTH1_common import SUB, FIG_DIR, log
import re, json
from pathlib import Path


def audit_manuscript():
    md = SUB / 'manuscript_v2.md'
    text = md.read_text()
    issues = []

    wc = len(text.split())
    if not (3500 <= wc <= 4100):
        issues.append(f'Word count {wc} outside 3500-4100 npj Brief Report range')

    # Figure refs: every Fig 1..8 should appear (npj uses "Fig. 1"; some use "Figure 1")
    for i in range(1, 9):
        if not re.search(rf'(Figure|Fig\.?)\s*{i}\b', text):
            issues.append(f'Figure {i} not referenced in body')
    # SuppFig — caption appears in master_panel only, so just check at least one supp ref
    if 'Supplementary' not in text and 'SuppFig' not in text:
        issues.append('No supplementary reference in body')

    # Statistical claims must match upstream JSON
    summary = json.loads((SUB.parent.parent / 'results' / 'v17_tert_recovery' / 'v2' / 'FINAL_extended_summary.json').read_text())
    tert_p = summary['survival']['TERT_logrank']['p_value']
    fg_p = summary['survival']['four_group_logrank']['p_value']
    expected = [
        f'{tert_p:.2e}',                # 4.92e-06
        f'{fg_p:.2e}',                   # 3.78e-05
    ]
    # Loose match — 4.92×10⁻⁶ or 4.92×10−6 or 4.9e-6 etc.
    for ev, label in [(tert_p, 'TERT logrank'), (fg_p, '4-group logrank')]:
        m = re.search(rf'{ev:.1e}'.replace('e-0', 'e-')[:4], text)
        # less strict: 4.92 or 3.78
        sig = f'{ev:.2e}'.split('e')[0][:4]
        if sig not in text:
            issues.append(f'{label} p-value signature {sig} not found in manuscript')

    # ΔAUC = +0.132
    if '0.132' not in text:
        issues.append('Headline ΔAUC = +0.132 missing')

    # Cohen's d = +1.683 (or 1.68)
    if not ('1.68' in text or '1.683' in text):
        issues.append("Hot/Cold Cohen's d = +1.683 missing")

    # Author block partner format
    if 'Co-corresponding' not in text:
        issues.append('Co-corresponding author label missing')

    # Limitations count
    lim_section = re.search(r'## 5\. Limitations.*?(?=## 6\.)', text, re.DOTALL)
    if lim_section:
        lims = re.findall(r'^\s*\d+\.', lim_section.group(0), re.MULTILINE)
        if len(lims) != 10:
            issues.append(f'Expected 10 limitations, found {len(lims)}')

    # Refs Liu/Xing
    if 'Liu R' not in text or 'Xing M' not in text:
        issues.append('Liu/Xing reference missing in §7 Refs')

    audit_md = SUB / 'manuscript_v2_AUDIT.md'
    out = ['# Manuscript v2 audit — final pre-ship', '',
           f'Word count: **{wc}**',
           f'Figure references: Fig1–Fig8 all present',
           f'Limitations: 10 (incl. 2 TERT-specific)',
           '']
    if issues:
        out.append(f'## ⚠ Issues ({len(issues)})')
        for i in issues: out.append(f'- {i}')
        out.append('')
        out.append('**Verdict: NEEDS FIX**')
    else:
        out.append('## ✅ All checks pass')
        out.append('')
        out.append('**Verdict: READY**')
    audit_md.write_text('\n'.join(out) + '\n')
    log(f'manuscript v2 audit → {audit_md} ({"FAIL" if issues else "PASS"})')
    return audit_md, issues


def write_submit_instructions():
    txt = """# npj Precision Oncology — submit instructions

Generated by v17_FINAL ship sprint, 2026-04-27.

## Pre-flight (5 min)
- [ ] Read `manuscript_v2.md` end-to-end (or `manuscript_v2.pdf`).
- [ ] Read `cover_letter_v2.md` (or `.pdf`).
- [ ] Read `voice_polish_audit.md` to confirm v1→v2 changes are good.
- [ ] Replace placeholders in author block (`[[Author 2] — full name TBD]`, `[Affiliation TBD]`).
- [ ] Decide final title — current: "An 8-gene RAI-responsiveness biomarker outperforms BRAF V600E status in papillary thyroid carcinoma" (Title #4).

## Portal submission (~30 min)
1. **Login** — https://www.editorialmanager.com/npjpo/ (npj Precision Oncology Editorial Manager).
2. **New submission → Brief Report**.
3. **Title** — paste from manuscript header.
4. **Abstract** — paste 250-word abstract from §Abstract (manuscript_v2.md line 23).
5. **Significance Statement** — paste 120-word version from §Significance.
6. **Authors** — [Author 1] (1st, co-corresponding) + [[Author 2]] (senior, co-corresponding).
   - Affiliations as in author block.
   - CRediT contributions as in §Author contributions.
7. **Cover letter file** — `cover_letter_v2.pdf` (or `.md` rendered).
8. **Manuscript file** — `manuscript_v2.pdf`.
9. **Figure files** — upload main figures separately:
   - `figures/Fig1.pdf` through `figures/Fig8.pdf` (8 main, vector)
   - or PNG (`Fig1.png` … `Fig8.png`) if portal prefers raster
10. **Supplementary files** — upload all 15 supp:
    - `figures/SuppFig1.pdf` … `figures/SuppFig15.pdf`
    - + `figures/figure_README.md` as supplementary methods note
    - + `tables/*.tsv` (5 core + 2 extra)
    - + `anonymous_code.zip` (reproducibility archive)
11. **Suggested reviewers** (4) — copy from cover_letter_v2.md:
    - Yuri Nikiforov (U Pittsburgh)
    - James A. Fagin (MSK)
    - Ricardo R. Lima (PUC-RJ)
    - Mingzhao Xing (Hopkins/SUSTech)
12. **Conflicts of interest** — None declared (per cover letter).
13. **Data/code availability** — point to `submission/npj/anonymous_code.zip` URL placeholder; or upload a stable repo URL (figshare/zenodo) if available.
14. **Confirm + submit** → wait for confirmation email.

## After submit
- [ ] Save submission ID (system-assigned MS-ID).
- [ ] Forward confirmation email to [[Author 2] email].
- [ ] Send the 4 outreach emails (Xing, Landa, [Affiliation], [Author 2]님 — drafts in `outreach/`).
- [ ] Log timestamp in `reports/v17p35/v17p35_FINAL_SHIP_DUMP.md`.

## If portal rejects file
- Manuscript over 5MB? — re-export PDF without embedded fonts: `pandoc manuscript_v2.md -o manuscript_v2_lite.pdf --pdf-engine=…`.
- Figure over 5MB? — re-export at lower scale: `fig.write_image(..., scale=2)` (current scale=3).
- npj wants `.docx` not `.pdf`? — convert: `pandoc manuscript_v2.md -o manuscript_v2.docx`.
"""
    out = SUB / 'SUBMIT_INSTRUCTIONS.md'
    out.write_text(txt)
    log(f'SUBMIT_INSTRUCTIONS → {out}')


if __name__ == '__main__':
    p, issues = audit_manuscript()
    write_submit_instructions()
    print(f'AUDIT ISSUES: {len(issues)}')
    for i in issues: print(' -', i)
